// Define UnitType if not imported from elsewhere
export type UnitType = 'g' | 'kg' | 'ml' | 'l' | 'piece' | 'serving';

export type ProductInput = {
    id?: number;
    name: string;
    nameSearch?: string;
    active: boolean;
    energy?: number;
    protein?: number;
    fat?: number;
    saturatedFattyAcid?: number;
    carbohydrates?: number;
    sugar?: number;
    starch?: number;
    dietaryFiber?: number;
    salt?: number;
    sodium?: number;
    k?: number;
    ca?: number;
    p?: number;
    fe?: number;
    polyols?: number;
    remarks?: string;
    cholesterol?: number;
    omega6?: number;
    omega3?: number;
    mov?: number;
    eov?: number;
    vitD?: number;
    vitC?: number;
    vitB12?: number;
    vitB6?: number;
    vitB2?: number;
    vitB1?: number;
    vitA?: number;
    mg?: number;
    water?: number;
    isFood?: boolean;
    remarksCarbohydrates?: string;
    hash?: string;
    userStudyId?: number;
    unit?: UnitType;
    synonyms?: string;
    brands?: string;
    brandsSearch?: string;
    glucose?: number;
    fructose?: number;
    excessFructose?: number;
    lactose?: number;
    sorbitol?: number;
    mannitol?: number;
    fructans?: number;
    gos?: number;
    token?: string;
    tokenDeleted?: string;
    bron?: string;
    userId?: number;
    deleted?: boolean;
    categories?: string;
    barcode?: string;
    mergedTo?: number;
    created?: Date | string;
    updated?: Date | string;
    appVer?: string;
};